### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by balintking** [kir-dev/collage-schedule-planner#22]
### Description
Develop a Calendar component to display the assignments of the user.

> The component could allow users to view events by week, and month.

### Tasks
- [ ] Research, what library would do the trick. xd
- [ ] Create the basic structure of the Calendar component.
- [ ] Add the ability to display events on the calendar.
- [ ] Style the Calendar component to fit with the overall design of the application.

### Acceptance Criteria
- Users should be able to view the calendar in day, week, and month formats.
- Events should be displayed accurately on the calendar.
- The component should be visually appealing and consistent with the application's theme.
