### ISSUE TITLE
Footer component

### ISSUE THREAD

**Issue by balintking** [kir-dev/collage-schedule-planner#23]
### Description
Create a Footer component to be displayed at the bottom of each page. The Footer should contain links to important information and resources, as well as the made by Kir-Dev logo (contact me for resources)

### Tasks
- [ ] Develop the basic structure of the Footer component.
- [ ] Add links to important information and resources.
- [ ] Ensure the Footer is responsive and works well on all devices.
- [ ] Style the Footer to match the overall design of the application.

### Acceptance Criteria
- The Footer should be present on all pages.
- Links in the Footer should be functional.
- The design should be consistent with the rest of the application.
