### ISSUE TITLE
Event details component

### ISSUE THREAD

**Issue by balintking** [kir-dev/collage-schedule-planner#25]
### Description
Develop a component to display detailed information about a specific event when clicked on the calendar.

### Tasks
- [ ] Create the basic structure of the Event Details component.
- [ ] Implement functionality to display detailed information about an event.
- [ ] Make sure, the component is responsive.
- [ ] Style the Event Details component to match the overall design of the application.

### Acceptance Criteria
- Users should be able to view detailed information about events.
- The component looks good on all devices independently of its size.
- The design should be consistent with the application's theme.
